name: Scheduled Secret Scan Dispatch

on:
  schedule:
    - cron: '0 0 * * 0'    # weekly (Sunday 00:00 UTC)
    - cron: '0 1 1 * *'    # monthly (1st day 01:00 UTC)
    - cron: '0 2 1 */3 *'  # quarterly (every 3 months, 01:00 UTC on day 1)
  workflow_dispatch: {}

jobs:
  dispatch-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch `secret-scan.yml`
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: secret-scan.yml
          ref: main